"""add chart status

Revision ID: 38b1f13b029e
Revises: 6fb088b51b6e
Create Date: 2025-12-16 03:17:41.923525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38b1f13b029e'
down_revision: Union[str, Sequence[str], None] = '6fb088b51b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charts', 'original_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('charts', 'result_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_charts_status'), table_name='charts')
    op.create_index(op.f('ix_charts_user_id'), 'charts', ['user_id'], unique=False)
    op.drop_constraint(op.f('charts_user_id_fkey'), 'charts', type_='foreignkey')
    op.drop_column('charts', 'preview_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('preview_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('charts_user_id_fkey'), 'charts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_charts_user_id'), table_name='charts')
    op.create_index(op.f('ix_charts_status'), 'charts', ['status'], unique=False)
    op.alter_column('charts', 'result_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('charts', 'original_path',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
